services:
  - type: web
    name: adamcoolsprojet
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-file -
