services:
  - type: web
    name: gexora
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-file -
    envVars:
      - key: RENDER_DATA_DIR
        value: /var/data
      - key: SITE_NAME
        value: Gexora
      - key: SITE_URL
        value: https://gexora.onrender.com
    disk:
      name: gexora-data
      mountPath: /var/data
      sizeGB: 1
